cleub/urls.py
from django.conf.urls import url
from . import views
app_name='cleub'

urlpatterns = [
    
    url(r'^$', views.index, name='index'),
    url(r'about/$', views.about, name='about'),
    url(r'^services/$', views.services, name='services'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^product/$', views.product, name='product'),
    url(r'^contactus/$', views.contactus, name='contactus'),

    
]

cleubsoft/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/', include('cleub.urls')),
	url(r'^', include('cleub.urls')),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^products/', include('products.urls')),
	url(r'^categories/', include('products.urls_categories')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}

{% block content %}

<section class="section-page-header">
    <div class="container">
        <div class="row">


        </div>
    </div>
</section>
<!-- /Section: Page Header -->

<!-- Main -->
<main class="main-container">
    <div class="container">

        <div class="row">

            <!-- Our History -->
            <div class="col-md-8">

                <h3 class="title">About Us</h3><hr>
                <p class="text-justify">
                   
              Cleub develop and manufacture wireless products, which are not only cost effective, but are also energy efficient, smart and elegant.

Lots of big companies in the market of home automation, manufacture complete modules so as to make home automated and wireless. But they are bounded by compatibility. They require appliances which are wireless and compatible to their modules or their product.This makes us unique and our market huge and ever-lasting, as new products will never end coming and people will never stop buying them.

They restrict the selection of appliance for the customer and not every person can buy them, because what about the already installed appliances or products which the customers have already bought.

Also, not every popular company manufactures wireless products. We at Cleub does not let people face this problem. We do not let people purchase high price, wireless, smart products, but make their already purchased products or appliances wireless and smart. People will purchase the body of the appliance and we put brains in it.
                </p>

                <p class="text-justify">
                  
                </p>

            </div>
            <!-- Our History -->

            <!-- Our Skills -->
            <div class="col-md-4">

                <h3 class="title">Services we Offer </h3>

                <div class="skills">


                    <div class="title"> Home Automation</div>
                    <div class="progress">
                        <div style="width: 100%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80"
                             role="progressbar" class="progress-bar fadeInLeft wow" data-wow-duration="1.3s" data-wow-delay="0.3s"></div>
                    </div>

                    <div class="title"> Home Security </div>
                    <div class="progress">
                        <div style="width: 100%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="75"
                             role="progressbar" class="progress-bar fadeInLeft wow" data-wow-duration="1.3s" data-wow-delay="0.6s"></div>
                    </div>

                    <div class="title"> Lighting</div>
                    <div class="progress">
                        <div style="width: 100%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="85"
                             role="progressbar" class="progress-bar fadeInLeft wow" data-wow-duration="1.3s" data-wow-delay="0.9s"></div>
                    </div>

                </div>
            </div>
            <!-- /Our Skills -->


    <br>
    <br>
      <br>
    <br>
    <br>
</main>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Page title -->
    <title>CleubLife | A smart home automation solution</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static 'cleub/images/l.gif' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'cleub/css/newstyle.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'cleub/css/newcss.css' %}">

</head>
<body>

<!-- Preloader -->
<div id="preloader">
    <div class="loader"></div>
</div>
<!-- /Preloader -->

<!-- Header -->
<header id="home" class="header">

    <!-- Navigation -->
    <nav id="navigation" class="navbar affix">

        <!-- Company Information -->
        <div class="information hidden-sm hidden-xs">
            <div class="container">
                <div class="row">

                    <!-- Feedback -->
                    <div class="col-md-7">
                        <a href="https://maps.google.com/maps?q=221B+Baker+Street,+London,+United+Kingdom&amp;hl=en&amp;t=v&amp;hnear=221B+Baker+St,+London+NW1+6XE,+United+Kingdom" class="iframe-popup"><span class="icon icon_pin_alt"></span> Shri Mata Vaishno Devi University</a>
                        <a href="#"><span class="icon icon_mail_alt"></span> support@cleublife.com</a>
                        <a href="#"><span class="icon icon_phone"></span> +91 9858900094</a>
                    </div>
                    <!-- /Feedback -->

                    <!-- Social -->
                    <div class="col-md-5">
                        <ul class="social">
                            <li><a href="https://www.facebook.com/CleubInc/" class="fa fa-fw fa-facebook"></a></li>
                            <li><a href="#" class="fa fa-fw fa-twitter"></a></li>
                            <li><a href="#" class="fa fa-fw fa-google-plus"></a></li>
                           
                        </ul>
                    </div>
                    <!-- /Social -->

                </div>
            </div>
        </div>
        <!-- /Company Information -->

        <div class="container">

            <div class="row">
                <div class="col-md-12">

                    <!-- Navigation Header -->
                    <div class="navbar-header">

                        <!-- Toggle Button -->
                        <button type="button"
                                class="navbar-toggle collapsed"
                                data-toggle="collapse"
                                data-target="#main-menu"
                                aria-expanded="false"
                                aria-controls="main-menu">

                            <span class="sr-only">Toggle Navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>

                        </button>
                        <!-- /Toggle Button -->

                        <!-- Brand -->
                        <a href="#" class="brand">

                            <!-- Logo Big -->
                            <img src="{% static 'cleub/images/l.gif' %}" class="logo-big" alt="" style="height: 55px;width:90px;">
                            <!-- /Logo Big -->

                            <!-- Logo Small -->
                            <img src="{% static 'cleub/images/l.gif' %}" class="logo-small" alt="" style="height: 45px;width:60px;">
                          

                        </a>
                        <!-- /Brand -->

                    </div>
                    <!-- /Navigation Header -->

                    <!-- Navigation -->
                    <div id="main-menu" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'cleub:index' %}">Home</a></li>
                            <li><a href='{% url "products" %}'>product</a></li>
                           <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
    
      </form>
                            <li><a href="">Bag&nbsp; <i class="fa fa-shopping-bag" aria-hidden="true"></i></a></li>
                            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {% if request.user.is_authenticated %}{{user}}  {% else %}Customer {% endif %} <span class="caret"></span></a>
          <ul class="dropdown-menu">
          {% if request.user.is_authenticated %}
                  <li><a href="#">Show Order</a></li>
                     <li><a href="/accounts/logout/">Logout</a></li>  
                     {% else %}
              <li><a href="/accounts/login/">Log In</a></li>
            <li><a href="/accounts/signup/">Sign UP</a></li>
           {% endif %}
            <li role="separator" class="divider"></li>
            
          </ul>
        </li>
                            
                        </ul>
                    </div>
                    <!-- /Navigation -->

                </div>
            </div>

        </div>
    </nav>
    <!-- /Navigation -->

</header>

{% block content %}{% endblock %}

<!-- Footer -->
<footer class="footer section-small">
    <div class="container">
        <div class="row">

            <!-- Footer Column -->
            <div class="col-md-3 col-xs-6 footer-col">

                <!-- Footer Logo -->
                <div class="logo">
                  <img src="{% static 'cleub/images/l.gif' %}" class="logo-small" alt="" style="height: 45px;width:60px;">
                          
                </div>
                <!-- /Footer Logo -->
                <hr>
                <!-- Footer Text -->
                <p class="text">
                    We Take Care Of Our Customer Requirements & Comfortibility.
                </p>
                <!-- /Footer Text -->

                <hr>

                <!-- Copyright -->
                <p class="copyright">
                    Copyright &copy; 2016-2017 <strong>CleubLife</strong>
                </p>
                <!-- /Copyright -->

                <!-- Footer Social -->
                <ul class="social-inline">
                    <li><a href="#" class="fa fa-fw fa-facebook"></a></li>
                    <li><a href="#" class="fa fa-fw fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-fw fa-google-plus"></a></li>
                 
                </ul>
                <!-- /Footer Social -->

            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-md-3 col-xs-6 footer-col">

                <h3 class="title">CleubLife </h3>

             
                 <ul class="menu">
 <li><a href="#">CleubLife Term &amp; Conditions</a></li>
                    <li><a href="#">Send Feedback</a></li>
                    <li><a href="#">We are hiring</a></li>
                    <li><a href="#">privacy policy</a></li>
                      </ul>
            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-md-2 col-xs-6 footer-col">

                <h3 class="title">Site Menu</h3>

                <!-- Footer Menu -->
                <ul class="menu">
                    <li><a href="#">Home</a></li>
                    <li><a href="{% url 'cleub:about' %}">About</a></li>
                    <li><a href="{% url 'cleub:contactus' %}">Contact</a></li>
                </ul>
                <!-- /Footer Menu -->

            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-md-4 col-xs-6 footer-col">

                <h3 class="title">Know our <span class="text-theme">latest product</span></h3>

                <!-- Footer Signup Form -->
                <div class="signup-form">
                    <form method="post" class="form-inline">
                        <div class="form-group">
                           {% csrf_token %}
                            {{ form1|crispy }}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-theme"><i class="fa fa-fw fa-envelope"></i></button>
                        </div>
                    </form>

                </div>
                <!-- /Footer Signup Form -->

                <hr>

                <!-- Footer Tags -->
                <div class="tags">
                  
                </div>
                <!-- /Footer Tags -->

            </div>
            <!-- /Footer Column -->

        </div>
    </div>
</footer>
<!-- /Footer -->

<!-- Scroll To Top -->
<div id="scroll-to-top" class="scroll-to-top">
    <i class="icon fa fa-angle-up"></i>
</div>
<!-- /Scroll To Top -->

<!-- Modal: Result Message -->
<div class="modal fade" id="result" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title">Sending message</h4>
            </div>

            <div class="modal-body">

                <div class="result-icon">
                    <div class="icon-border">
                        <svg version="1.1" xmlns="" viewBox="0 0 16 16" preserveAspectRatio="none">
                            <circle cx="8" cy="8" r="6.215" transform="rotate(90 8 8)"></circle>
                        </svg>
                        <i class="icon fa fa-check"></i>
                    </div>
                </div>

                <p class="modal-result h4 text-center"></p>
            </div>

        </div>
    </div>
</div>

<script src="{% static 'cleub/js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'cleub/js/bootstrap.min.js' %}"></script>
<script src="{% static 'cleub/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'cleub/js/wow.min.js' %}"></script>
<script src="{% static 'cleub/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.appear.js' %}"></script>
<script src="{% static 'cleub/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'cleub/js/general.js' %}"></script>
<!-- /SCRIPTS -->




</div>

</body>

</html>

templates/basedown.html
<!DOCTYPE html>
<html>
<head>
	
</head>
<body>

<!-- Footer -->
<footer class="footer section-small">
    <div class="container">
        <div class="row">

            <!-- Footer Column -->
            <div class="col-md-3 col-xs-6 footer-col">

                <!-- Footer Logo -->
                <div class="logo">
                    <img src="images/logo.png" alt="">
                </div>
                <!-- /Footer Logo -->

                <!-- Footer Text -->
                <p class="text">
                    It is a long established fact that a reader will be distracted by the readable.
                </p>
                <!-- /Footer Text -->

                <hr>

                <!-- Copyright -->
                <p class="copyright">
                    Copyright &copy; 2015-2016 <strong>Valery Timofeev</strong>
                </p>
                <!-- /Copyright -->

                <!-- Footer Social -->
                <ul class="social-inline">
                    <li><a href="#" class="fa fa-fw fa-facebook"></a></li>
                    <li><a href="#" class="fa fa-fw fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-fw fa-google-plus"></a></li>
                    <li><a href="#" class="fa fa-fw fa-dribbble"></a></li>
                    <li><a href="#" class="fa fa-fw fa-pinterest"></a></li>
                </ul>
                <!-- /Footer Social -->

            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-md-3 col-xs-6 footer-col">

                <h3 class="title">Latest From <span class="text-theme">Blog</span></h3>

                <!-- Footer Post -->
                <div class="media post">
                    <div class="media-left">
                        <div class="image">
                            <img src="images/last-post-01.jpg" alt="">
                        </div>
                    </div>
                    <div class="media-body">
                        <p class="text">
                            It is a long established fact that a reader will be distracted.
                        </p>
                        <a href="#">Read more</a>
                    </div>
                </div>
                <!-- /Footer Post -->

                <!-- Footer Post -->
                <div class="media post">
                    <div class="media-left">
                        <div class="image">
                            <img src="images/last-post-02.jpg" alt="">
                        </div>
                    </div>
                    <div class="media-body">
                        <p class="text">
                            It is a long established fact that a reader will be distracted.
                        </p>
                        <a href="#">Read more</a>
                    </div>
                </div>
                <!-- /Footer Post -->

            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-md-2 col-xs-6 footer-col">

                <h3 class="title">Site Menu</h3>

                <!-- Footer Menu -->
                <ul class="menu">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Features</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <!-- /Footer Menu -->

            </div>
            <!-- /Footer Column -->

            <!-- Footer Column -->
            <div class="col-md-4 col-xs-6 footer-col">

                <h3 class="title">Signup to <span class="text-theme">Newsletter</span></h3>

                <!-- Footer Signup Form -->
                <div class="signup-form">
                    <form method="post" class="form-inline">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Your E-mail...*" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-theme"><i class="fa fa-fw fa-envelope"></i></button>
                        </div>
                    </form>

                </div>
                <!-- /Footer Signup Form -->

                <hr>

                <!-- Footer Tags -->
                <div class="tags">
                    <a href="#" class="tag">web</a>
                    <a href="#" class="tag">design</a>
                    <a href="#" class="tag">clean</a>
                    <a href="#" class="tag">minimal</a>
                    <a href="#" class="tag">pixel perfect</a>
                    <a href="#" class="tag">blog</a>
                    <a href="#" class="tag">gallery</a>
                </div>
                <!-- /Footer Tags -->

            </div>
            <!-- /Footer Column -->

        </div>
    </div>
</footer>
<!-- /Footer -->

<!-- Scroll To Top -->
<div id="scroll-to-top" class="scroll-to-top">
    <i class="icon fa fa-angle-up"></i>
</div>
<!-- /Scroll To Top -->

<!-- Modal: Result Message -->
<div class="modal fade" id="result" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title">Sending message</h4>
            </div>

            <div class="modal-body">

                <div class="result-icon">
                    <div class="icon-border">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" preserveAspectRatio="none">
                            <circle cx="8" cy="8" r="6.215" transform="rotate(90 8 8)"></circle>
                        </svg>
                        <i class="icon fa fa-check"></i>
                    </div>
                </div>

                <p class="modal-result h4 text-center"></p>
            </div>

        </div>
    </div>
</div>
<!-- /Modal: Result Message -->

<!-- SCRIPTS -->
<script src="{% static 'cleub/js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'cleub/js/bootstrap.min.js' %}"></script>
<script src="{% static 'cleub/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'cleub/js/wow.min.js' %}"></script>
<script src="{% static 'cleub/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'cleub/js/jquery.appear.js' %}"></script>
<script src="{% static 'cleub/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'cleub/js/general.js' %}"></script>
<!-- /SCRIPTS -->


<!-- TODO: Remove this block, Demo-version only -->
<!-- Styleswitcher -->
<div id="styleswitcher" class="styleswitcher">
    <div class="styleswitcher-content">

        <h4 class="styleswitcher-title">Color Presets</h4>
        <div class="styleswitcher-block">
            <ul class="styleswitcher-list-colors">
                <li><a href="javascript: switchStyle('theme-persimmon')" style="background: #ff5555;" title="Persimmon"></a></li>
                <li><a href="javascript: switchStyle('theme-atomic-tangerine')" style="background: #ff9e55;" title="Atomic Tangerine"></a></li>
                <li><a href="javascript: switchStyle('theme-yellow-sea')" style="background: #fab000;" title="Yellow Sea"></a></li>
                <li><a href="javascript: switchStyle('theme-rio-grande')" style="background: #aed605;" title="Rio Grande"></a></li>
                <li><a href="javascript: switchStyle('theme-vida-loca')" style="background: #38b71f;" title="Vida Loca"></a></li>
                <li><a href="javascript: switchStyle('theme-mountain-meadow')" style="background: #1fb768;" title="Mountain Meadow"></a></li>
                <li><a href="javascript: switchStyle('theme-java')" style="background: #1fb7a4;" title="Java"></a></li>
                <li><a href="javascript: switchStyle('theme-mariner')" style="background: #3274cd;" title="Mariner"></a></li>
                <li><a href="javascript: switchStyle('theme-medium-purple')" style="background: #996de9;" title="Medium Purple"></a></li>
                <li><a href="javascript: switchStyle('theme-lavender-magenta')" style="background: #e94de4;" title="Lavender Magenta"></a></li>
            </ul>
        </div>

        <h4 class="styleswitcher-title">Navigation Style</h4>
        <div class="styleswitcher-block">
            <select id="styleswitcher-navbar-style">
                <option value="style-1">Default</option>
                <option value="style-2">Fill</option>
                <option value="style-3">Underline</option>
            </select>
        </div>

    </div>

    <div class="styleswitcher-button vertical-middle"><i class="fa fa-gear"></i></div>
</div>

<link rel="stylesheet" type="text/css" href="demo/styleswitcher.css" property="">
<script src="demo/styleswitcher.js"></script>
 <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter35435255 = new Ya.Metrika({ id:35435255, clickmap:true, trackLinks:true, accurateTrackBounce:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/35435255" style="position:absolute; left:-9999px;" alt="" /></div></noscript> 
</body>
</html>

templates/contactus.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}

<section class="section-page-header">
    <div class="container">
        <div class="row">

            <!-- Page Title -->
           
            <!-- /Breadcrumbs -->

        </div>
    </div>
</section>
<!-- /Section: Page Header -->

<!-- Main -->
<main class="main-container">
    <div class="container">

        <div class="row">

            <!-- Contact Form -->
            <div class="col-md-8 contact-form fadeIn wow" data-wow-duration="1.3s">

                <h3 class="title">Send Message</h3>
 <form class="form-group" method="post">
            <div class="row">

            <div class="col-xs-12 col-sm-6 col-md-8">
            {% csrf_token %}
            {{ form|crispy }}
            </div>

            </div>
           <div class="row">
                            <div class="form-group col-md-12 text-center">
                                <button type="submit" class="btn btn-theme"><i class="fa fa-fw fa-paper-plane-o"></i> Send Message</button>
                            </div>
                        </div>

                    </form>
            </div>
            <!-- /Contact Form -->

            <!-- Address -->
            <div class="col-md-4 fadeIn wow" data-wow-duration="1.3s" data-wow-delay="0.7s">

                <h3 class="title">Information</h3>
                <p>
                    Drop us mail we will contact you soon.
                </p>

                <ul class="contact-information">
                    <li><i class="icon fa fa-fw fa-globe"></i> <span> Office</span><br> 2nd Floor B-C Junction 
                                                                                    Business Incubation Center 
                                                                                    SMVD University Katra 
                                                                                    Jammu, J&K-182320</li>
                    <li><i class="icon fa fa-fw fa-envelope"></i><span>E-mail</span> support@cleubsoft.com</li>
                    <li><i class="icon fa fa-fw fa-phone"></i><span>Phone</span> +91 9858900094</li>
                </ul>

            </div>
            <!-- /Address -->

        </div>

    </div>

    

</main>
<!-- /Main -->
{% endblock  %}

templates/thanks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}

<section class="section-page-header">
    <div class="container">
        <div class="row">

            <!-- Page Title -->
            <div class="col-md-8">
                <h1 class="title">Thank You </h1>
                <div class="subtitle">We will look forward to your response</div>
            </div>
            <!-- /Page Title -->

            <!-- Breadcrumbs -->
            <div class="col-md-4">
                <ul class="breadcrumb">
                    <li><i class="fa fa-fw fa-home"></i> <a href="#">Home</a></li>
                    <li>Contact</li>
                </ul>
            </div>
            <!-- /Breadcrumbs -->

        </div>
    </div>
</section>
<!-- /Section: Page Header -->

<!-- Main -->
<main class="main-container">
    <div class="container">

        <div class="row">
            <!-- /Contact Form -->

            <!-- Address -->
            <div class="col-md-12 fadeIn wow" data-wow-duration="1.3s" data-wow-delay="0.7s">

                <h3 class="title">Information</h3>
                <p>
                    Drop us mail we will contact you soon.
                </p>

                <ul class="contact-information">
                    <li><i class="icon fa fa-fw fa-globe"></i> <span> Office</span><br> 2nd Floor B-C Junction 
                                                                                    Business Incubation Center 
                                                                                    SMVD University Katra 
                                                                                    Jammu, J&K-182320</li>
                    <li><i class="icon fa fa-fw fa-envelope"></i><span>E-mail</span> support@cleubsoft.com</li>
                    <li><i class="icon fa fa-fw fa-phone"></i><span>Phone</span> +91 9858900094</li>
                </ul>

            </div>
            <!-- /Address -->

        </div>

    </div>

    

</main>
<!-- /Main -->
{% endblock  %}